name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div class="tradingview-widget-container__widget"></div>
  <div class="tradingview-widget-copyright"><a href="https://id.tradingview.com/symbols/EURUSD/technicals/" rel="noopener" target="_blank"><span class="blue-text">Analisis Teknikal untuk EURUSD</span></a> oleh TradingView</div>
  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-technical-analysis.js" async>
  {
  "interval": "1m",
  "width": "250",
  "isTransparent": false,
  "height": "450",
  "symbol": "FX:EURUSD",
  "showIntervalTabs": true,
  "locale": "id",
  "colorTheme": "light"
}
  </script>
</div>
<!-- TradingView Widget END -->
